apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJjaHJvbm9ydXMiLCJwYXNzd29yZCI6ImRja3JfcGF0XzJpUUpxWlZUWl9hLUppM2N3WXYyV1dEaGpNbyIsImF1dGgiOiJZMkZ5YkhGbkxtRmtiV2x1UVhKbGJHRjBaMjl2UjBCTkt6QXhVelpWWlhKNWMyTmhZMmhUY0c0PSJ9fQ==
