apiIngress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  enabled: true
  extraTls:
  - hosts:
    - openim1.server.top
    secretName: webapitls
  hostname: openim1.server.top
  ingressClassName: nginx
  path: /im-minio-api(/|$)(.*)
  pathType: ImplementationSpecific
  servicePort: minio-api
auth:
  rootPassword: openIM123
  rootUser: root
defaultBuckets: openim
global:
  imageRegistry: public.ecr.aws
  storageClass: gp3
ingress:
  enabled: false
  extraTls:
  - hosts:
    - openim.minio.console
    secretName: openim2tls
  hostname: openim.minio.console
  ingressClassName: nginx
  path: /
  servicePort: minio-console
metrics:
  serviceMonitor:
    enabled: false
    labels:
      release: kube-prometheus-stack
mode: standalone
persistence:
  size: 1Gi
