config:
  api:
    listenIP: 0.0.0.0
    openImApiPort:
    - 80
  callback:
    addBlackBefore:
      enable: false
      failedContinue: true
      timeout: 5
    addFriendAfter:
      enable: false
      failedContinue: true
      timeout: 5
    addFriendAgreeBefore:
      enable: false
      failedContinue: true
      timeout: 5
    afterCreateGroup:
      enable: false
      failedContinue: true
      timeout: 5
    afterGroupMsgRead:
      enable: false
      failedContinue: true
      timeout: 5
    afterGroupMsgRevoke:
      enable: false
      failedContinue: true
      timeout: 5
    afterJoinGroup:
      enable: false
      failedContinue: true
      timeout: 5
    afterSendGroupMsg:
      enable: false
      failedContinue: true
      timeout: 5
    afterSendSingleMsg:
      enable: false
      failedContinue: true
      timeout: 5
    afterSetFriendRemark:
      enable: false
      failedContinue: true
      timeout: 5
    afterSetGroupMemberInfo:
      enable: false
      failedContinue: true
      timeout: 5
    afterUpdateUserInfoEx:
      enable: false
      failedContinue: true
      timeout: 5
    afterUserRegister:
      enable: false
      failedContinue: true
      timeout: 5
    beforeAddFriend:
      enable: false
      failedContinue: true
      timeout: 5
    beforeCreateGroup:
      enable: false
      failedContinue: true
      timeout: 5
    beforeInviteUserToGroup:
      enable: false
      failedContinue: true
      timeout: 5
    beforeMemberJoinGroup:
      enable: false
      failedContinue: true
      timeout: 5
    beforeSendGroupMsg:
      enable: false
      failedContinue: true
      timeout: 5
    beforeSendSingleMsg:
      enable: false
      failedContinue: true
      timeout: 5
    beforeSetFriendRemark:
      enable: false
      failedContinue: true
      timeout: 5
    beforeSetGroupMemberInfo:
      enable: false
      failedContinue: true
      timeout: 5
    beforeUpdateUserInfo:
      enable: false
      failedContinue: true
      timeout: 5
    beforeUpdateUserInfoEx:
      enable: false
      failedContinue: true
      timeout: 5
    beforeUserRegister:
      enable: false
      failedContinue: true
      timeout: 5
    deleteFriendAfter:
      enable: false
      failedContinue: true
      timeout: 5
    dismissGroup:
      enable: false
      failedContinue: true
      timeout: 5
    groupMsgRead:
      enable: false
      failedContinue: true
      timeout: 5
    importFriendsAfter:
      enable: false
      failedContinue: true
      timeout: 5
    importFriendsBefore:
      enable: false
      failedContinue: true
      timeout: 5
    joinGroup:
      enable: false
      failedContinue: true
      timeout: 5
    joinGroupAfter:
      enable: false
      failedContinue: true
      timeout: 5
    killGroupMember:
      enable: false
      failedContinue: true
      timeout: 5
    msgModify:
      enable: false
      failedContinue: true
      timeout: 5
    offlinePush:
      enable: false
      failedContinue: true
      timeout: 5
    onlinePush:
      enable: false
      failedContinue: true
      timeout: 5
    quitGroup:
      enable: false
      failedContinue: true
      timeout: 5
    removeBlackAfter:
      enable: false
      failedContinue: true
      timeout: 5
    revokeMsgAfter:
      enable: false
      failedContinue: true
      timeout: 5
    setGroupInfoAfter:
      enable: false
      failedContinue: true
      timeout: 5
    setGroupInfoBefore:
      enable: false
      failedContinue: true
      timeout: 5
    setMessageReactionExtensions:
      enable: false
      failedContinue: true
      timeout: 5
    singleMsgRead:
      enable: false
      failedContinue: true
      timeout: 5
    superGroupOnlinePush:
      enable: false
      failedContinue: true
      timeout: 5
    transferGroupOwner:
      enable: false
      failedContinue: true
      timeout: 5
    updateUserInfo:
      enable: false
      failedContinue: true
      timeout: 5
    url: null
    userKickOff:
      enable: false
      failedContinue: true
      timeout: 5
    userOffline:
      enable: false
      failedContinue: true
      timeout: 5
    userOnline:
      enable: false
      failedContinue: true
      timeout: 5
  chatPersistenceMysql: true
  chatRecordsClearTime: 0 2 * * 3
  envs:
    discovery: k8s
  groupMessageHasReadReceiptEnable: true
  im-admin:
    nickname:
    - imAdmin
    userID:
    - imAdmin
  iosPush:
    badgeCount: true
    production: false
    pushSound: xxx
  kafka:
    addr:
    - im-kafka:9092
    consumerGroupID:
      msgToMongo: mongo
      msgToMySql: mysql
      msgToPush: push
      msgToRedis: redis
    latestMsgToRedis:
      topic: latestMsgToRedis
    msgToPush:
      topic: msgToPush
    offlineMsgToMongo:
      topic: offlineMsgToMongoMysql
    password: proot
    username: root
  kubernetes:
    namespace: openim
  log:
    isJson: false
    isStdout: true
    remainLogLevel: 3
    remainRotationCount: 2
    rotationTime: 24
    storageLocation: ../logs/
    withStack: false
  longConnSvr:
    openImMessageGatewayPort:
    - 88
    openImWsPort:
    - 80
    websocketMaxConnNum: 100000
    websocketMaxMsgLen: 4096
    websocketTimeout: 10
  manager:
    nickname: null
    userID: null
  messageVerify:
    friendVerify: false
  mongo:
    address:
    - im-mongodb:27017
    database: openim_v3
    maxPoolSize: 300
    password: openIM123
    uri: mongodb://openIM:openIM123@im-mongodb-0.im-mongodb-headless:27017,im-mongodb-1.im-mongodb-headless:27017,im-mongodb-2.im-mongodb-headless:27017/openim_v3?replicaSet=rs0&maxPoolSize=300
    username: openIM
  msgCacheTimeout: 86400
  msgDestructTime: 0 2 * * *
  multiLoginPolicy: 1
  object:
    apiURL: https://openim1.server.top/api
    aws:
      accessKeyID: ""
      accessKeySecret: ""
      bucket: demo-9999999
      endpoint: ''''''
      publicRead: false
      region: us-east-1
    cos:
      bucketURL: https://temp-1252357374.cos.ap-chengdu.myqcloud.com
      publicRead: false
      secretID: ""
      secretKey: ""
      sessionToken: ""
    enable: minio
    kodo:
      accessKeyID: ""
      accessKeySecret: ""
      bucket: demo-9999999
      bucketURL: http://your.domain.com
      endpoint: http://s3.cn-east-1.qiniucs.com
      publicRead: false
      sessionToken: ""
    minio:
      accessKeyID: root
      bucket: openim
      endpoint: http://im-minio:9000
      publicRead: false
      secretAccessKey: openIM123
      sessionToken: ""
      signEndpoint: https://openim1.server.top/im-minio-api
    oss:
      accessKeyID: ""
      accessKeySecret: ""
      bucket: demo-9999999
      bucketURL: https://demo-9999999.oss-cn-chengdu.aliyuncs.com
      endpoint: https://oss-cn-chengdu.aliyuncs.com
      publicRead: false
      sessionToken: ""
  prometheus:
    apiPrometheusPort:
    - 90
    authPrometheusPort:
    - 90
    conversationPrometheusPort:
    - 90
    enable: true
    friendPrometheusPort:
    - 90
    grafanaUrl: https://openim2.server.top/
    groupPrometheusPort:
    - 90
    messageGatewayPrometheusPort:
    - 90
    messagePrometheusPort:
    - 90
    messageTransferPrometheusPort:
    - 90
    - 90
    - 90
    - 90
    pushPrometheusPort:
    - 90
    rtcPrometheusPort:
    - 90
    thirdPrometheusPort:
    - 90
    userPrometheusPort:
    - 90
  push:
    enable: getui
    fcm:
      serviceAccount: x.json
    geTui:
      appKey: ""
      channelID: ""
      channelName: ""
      intent: ""
      masterSecret: ""
      pushUrl: https://restapi.getui.com/v2/$appId
    jpns:
      appKey: null
      masterSecret: null
      pushIntent: null
      pushUrl: null
  redis:
    address:
    - im-redis-master:6379
    password: openIM123
    username: ""
  retainChatRecords: 365
  rpc:
    listenIP: 0.0.0.0
    registerIP: ""
  rpcPort:
    openImAuthPort:
    - 80
    openImConversationPort:
    - 80
    openImFriendPort:
    - 80
    openImGroupPort:
    - 80
    openImMessageGatewayPort:
    - 88
    openImMessagePort:
    - 80
    openImPushPort:
    - 80
    openImThirdPort:
    - 80
    openImUserPort:
    - 80
  rpcRegisterName:
    openImAuthName: openimserver-openim-rpc-auth:80
    openImConversationName: openimserver-openim-rpc-conversation:80
    openImFriendName: openimserver-openim-rpc-friend:80
    openImGroupName: openimserver-openim-rpc-group:80
    openImMessageGatewayName: openimserver-openim-msggateway:88
    openImMsgName: openimserver-openim-rpc-msg:80
    openImPushName: openimserver-openim-push:80
    openImThirdName: openimserver-openim-rpc-third:80
    openImUserName: openimserver-openim-rpc-user:80
  secret: openIM123
  singleMessageHasReadReceiptEnable: true
  tokenPolicy:
    expire: 90
  zookeeper:
    address:
    - 172.28.0.1:12181
    password: ""
    schema: openim
    username: ""
global:
  monitor:
    enabled: false
  sharedValues:
    msggatewayReplicaCount: 1
image:
  pullPolicy: Always
  repository: ghcr.io/openimsdk/openim-api
  tag: release-v3.6
ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  className: nginx
  enabled: true
  hosts:
  - host: openim1.server.top
    paths:
    - path: /api(/|$)(.*)
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - openim1.server.top
    secretName: webapitls
openim-msggateway:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/openim-msggateway
    tag: release-v3.6
openim-msggateway-proxy:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/openim-msggateway-proxy
    tag: v3.5.0
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
    className: nginx
    enabled: true
    hosts:
    - host: openim1.server.top
      paths:
      - path: /msg_gateway(/|$)(.*)
        pathType: ImplementationSpecific
    tls:
    - hosts:
      - openim1.server.top
      secretName: webapitls
openim-msgtransfer:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/openim-msgtransfer
    tag: release-v3.6
openim-push:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/openim-push
    tag: release-v3.6
openim-rpc-auth:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/openim-rpc-auth
    tag: release-v3.6
openim-rpc-conversation:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/openim-rpc-conversation
    tag: release-v3.6
openim-rpc-friend:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/openim-rpc-friend
    tag: release-v3.6
openim-rpc-group:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/openim-rpc-group
    tag: release-v3.6
openim-rpc-msg:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/openim-rpc-msg
    tag: release-v3.6
openim-rpc-third:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/openim-rpc-third
    tag: release-v3.6
openim-rpc-user:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/openim-rpc-user
    tag: release-v3.6
