global:
  imageRegistry: public.ecr.aws
  redis:
    password: openIM123
  storageClass: gp3
master:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 30
  persistence:
    size: 1Gi
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
  resources:
    limits:
      cpu: 1000m
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 4Gi
replica:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 30
  persistence:
    size: 1Gi
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
  replicaCount: 1
  resources:
    limits:
      cpu: 1000m
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 4Gi
