admin-rpc:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/chat-rpc-admin
    tag: release-v1.6
chat-api:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/chat-api-chat
    tag: release-v1.6
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
    className: nginx
    enabled: true
    hosts:
    - host: openim1.server.top
      paths:
      - path: /chat(/|$)(.*)
        pathType: ImplementationSpecific
    tls:
    - hosts:
      - openim1.server.top
      secretName: webapitls
chat-rpc:
  image:
    pullPolicy: Always
    repository: ghcr.io/openimsdk/chat-rpc-chat
    tag: release-v1.6
config:
  adminApi:
    listenIP: null
    openImAdminApiPort:
    - 80
  adminList:
  - adminID: null
    imAdmin: null
    nickname: null
  - adminID: null
    imAdmin: null
    nickname: null
  - adminID: null
    imAdmin: null
    nickname: null
  chatAdmin:
  - adminID: chatAdmin
    imAdmin: imAdmin
    nickname: chatAdmin
  chatApi:
    listenIP: null
    openImChatApiPort:
    - 80
  envs:
    discovery: k8s
  liveKit:
    key: ""
    liveKitUrl: wss://im-livekiturl:7880
    secret: ""
  log:
    isJson: false
    isStdout: true
    remainLogLevel: 6
    remainRotationCount: 2
    rotationTime: 24
    storageLocation: ../logs/
    withStack: false
  mongo:
    address:
    - im-mongo-mongodb:27017
    database: openim_v3
    maxPoolSize: 100
    password: openIM123
    uri: ""
    username: openIM
  openIMUrl: http://openim-server-openim-api
  redis:
    address:
    - im-redis-master:6379
    password: openIM123
    username: null
  rpc:
    listenIP: null
    registerIP: null
  rpcPort:
    openImAdminPort:
    - 80
    openImChatPort:
    - 80
  rpcRegisterName:
    openImAdminName: openim-chat-admin-rpc:80
    openImChatName: openim-chat-chat-rpc:80
  secret: openIM123
  tokenPolicy:
    expire: 86400
  verifyCode:
    ali:
      accessKeyId: ""
      accessKeySecret: ""
      endpoint: dysmsapi.aliyuncs.com
      signName: ""
      verificationCodeTemplateCode: ""
    len: 6
    mail:
      senderAuthorizationCode: ""
      senderMail: ""
      smtpAddr: smtp.qq.com
      smtpPort: 465
      title: ""
    maxCount: 10
    superCode: "666666"
    uintTime: 86400
    use: ""
    validCount: 5
    validTime: 300
  zookeeper:
    password: ""
    schema: openim
    username: ""
    zkAddr:
    - 127.0.0.1:12181
image:
  pullPolicy: Always
  repository: ghcr.io/openimsdk/chat-api-admin
  tag: release-v1.6
ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  className: nginx
  enabled: true
  hosts:
  - host: openim1.server.top
    paths:
    - path: /complete_admin(/|$)(.*)
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - openim1.server.top
    secretName: webapitls
