arbiter:
  enabled: true
architecture: replicaset
auth:
  databases:
  - openim_v3
  enabled: true
  passwords:
  - openIM123
  rootPassword: openIM123
  rootUser: root
  usernames:
  - openIM
backup:
  cronjob:
    storage:
      size: 1Gi
  enabled: false
global:
  imageRegistry: public.ecr.aws
  storageClass: gp3
livenessProbe:
  enabled: true
  failureThreshold: 8
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 30
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
pdb:
  create: true
  minAvailable: 2
persistence:
  size: 50Gi
readinessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 15
replicaCount: 3
resources:
  limits:
    cpu: 2000m
    memory: 10Gi
  requests:
    cpu: 2000m
    memory: 4Gi
