controller:
  replicaCount: 3
defaultReplicationFactor: 3
global:
  storageClass: gp3
metrics:
  jmx:
    enabled: true
  kafka:
    enabled: false
  serviceMonitor:
    enabled: false
minInsyncReplicas: 2
numPartitions: 8
offsetsTopicReplicationFactor: 3
provisioning:
  enabled: true
  numPartitions: 8
  replicationFactor: 3
  topics:
  - config:
      max.message.bytes: 64000
    name: toRedis
    partitions: 8
    replicationFactor: 3
  - config:
      max.message.bytes: 64000
    name: toMongo
    partitions: 8
    replicationFactor: 3
  - config:
      max.message.bytes: 64000
    name: toPush
    partitions: 8
    replicationFactor: 3
  - config:
      max.message.bytes: 64000
    name: toOfflinePush
    partitions: 8
    replicationFactor: 3
sasl:
  client:
    passwords: proot
    users:
    - root
  controller:
    password: gc5YfMRFZJ
  interbroker:
    password: hbe5wkZxQ0
transactionStateLogMinIsr: 2
transactionStateLogReplicationFactor: 3
